name: Publish Dockerfile
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latesr
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        registry: docker.pkg.github.com
        name: docker.pkg.github.com/fenixAlex88/Next.js/top-app-demo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "develop"